
# Token temporário de dev do Vault para o laboratório
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
data:
  token: cm9vdA== 
---
# Configura a conexão com o cofre local
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cofre-local
  namespace: default
spec:
  provider:
    vault:
      server: "[http://vault.vault.svc.cluster.local:8200](http://vault.vault.svc.cluster.local:8200)"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
# O manifesto seguro que vai para o GIT. Ele apenas MANDA buscar a senha.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo-db-secret-config
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cofre-local
    kind: SecretStore
  target:
    name: odoo-senha-banco # Este é o K8s Secret REAL que será criado dinamicamente
  data:
  - secretKey: senha-postgres
    remoteRef:
      key: secret/odoo
      property: senha