Estratégia de GitOps Seguro e Gerenciamento de Segredos

Este documento resolve a necessidade urgente de centralizar e automatizar deploys, removendo o gargalo de depender de uma única pessoa e eliminando a prática insegura de armazenar credenciais em texto plano (ConfigMaps) ou Base64 (Kubernetes Secrets nativos) no repositório.

Parte 1: Plano de Implantação para Produção (OCI / OKE)

A arquitetura alvo, fundamentada nas melhores práticas detalhadas no documento de referência, foca na total separação de responsabilidades, automação de reconciliação e segurança "Zero Trust".

1. Separação de Repositórios (App vs. Config)

Repositório de Aplicação: Código-fonte e Dockerfile.

Repositório de Configuração (GitOps): Apenas manifestos YAML. Desenvolvedores não editam diretamente na main.

2. Argo CD como Motor GitOps

O Argo CD roda no OKE. Ele monitora o repositório Git de Configuração. Se alguém alterar o Git (ex: mudar versão da imagem do Odoo de 15 para 16), o Argo CD detecta e aplica no cluster automaticamente.

3. Gestão Segura de Segredos (OCI Vault + External Secrets Operator)

Para não guardar senhas de banco de dados no Git:

O OCI Vault guarda as senhas reais.

O External Secrets Operator (ESO) roda no cluster, busca a senha no Vault (usando permissões do OKE Workload Identity) e injeta no Pod em tempo de execução.

Parte 2: Laboratório Prático de Prova de Conceito (Odoo + GitOps)

Para tangibilizar o processo, vamos fazer o deploy do Odoo e do seu banco de dados PostgreSQL na sua máquina, gerenciados pelo Argo CD e com a senha protegida no Vault.

Pré-requisitos

Minikube, kubectl, helm e git instalados.

Assumimos que o Passo 1, 2 e 4 do lab anterior foram feitos (Minikube rodando, ArgoCD instalado, Vault instalado e External Secrets Operator instalado). Se precisar, reinicie o minikube e aplique os comandos iniciais.

Passo 1: Guardando a Senha do Banco no Cofre (Vault)

O Odoo precisa de um banco PostgreSQL. Vamos definir uma senha para o banco e guardá-la DIRETAMENTE no cofre (ela nunca vai para o Git).

Execute no seu terminal:

# Salva a senha 'SuperSenhaOdoo123' dentro do Vault no caminho 'secret/odoo'
kubectl exec -it vault-0 -n vault -- vault kv put secret/odoo senha="SuperSenhaOdoo123"


Passo 2: Criando os Arquivos do Projeto (GitOps)

Crie uma pasta chamada gitops-odoo no seu computador e entre nela.

mkdir gitops-odoo
cd gitops-odoo


Agora, crie os 3 arquivos abaixo dentro dessa pasta. Eles representam a nossa infraestrutura.

Arquivo 1: 01-segredos.yaml (Faz a ponte com o cofre)

---
# Token temporário de dev do Vault para o laboratório
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
data:
  token: cm9vdA== 
---
# Configura a conexão com o cofre local
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cofre-local
  namespace: default
spec:
  provider:
    vault:
      server: "[http://vault.vault.svc.cluster.local:8200](http://vault.vault.svc.cluster.local:8200)"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
# O manifesto seguro que vai para o GIT. Ele apenas MANDA buscar a senha.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo-db-secret-config
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cofre-local
    kind: SecretStore
  target:
    name: odoo-senha-banco # Este é o K8s Secret REAL que será criado dinamicamente
  data:
  - secretKey: senha-postgres
    remoteRef:
      key: secret/odoo
      property: senha


Arquivo 2: 02-postgres.yaml (O Banco de Dados)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
spec:
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-senha-banco # Consome a senha injetada pelo ESO
              key: senha-postgres
        - name: POSTGRES_DB
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  ports:
  - port: 5432
  selector:
    app: odoo-db


Arquivo 3: 03-odoo.yaml (A Aplicação Odoo)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:16.0
        env:
        - name: HOST
          value: odoo-db # Aponta para o serviço do Postgres acima
        - name: USER
          value: odoo
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-senha-banco # Consome a mesma senha injetada pelo ESO
              key: senha-postgres
        ports:
        - containerPort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: NodePort
  ports:
  - port: 8069
    nodePort: 30069 # Porta fixa para acessarmos do nosso navegador
  selector:
    app: odoo


Passo 3: Subindo para o GitHub (A Fonte da Verdade)

Vá ao GitHub e crie um repositório Público vazio chamado gitops-odoo.
No seu terminal (dentro da pasta gitops-odoo), execute:

git init
git add .
git commit -m "feat: adiciona banco postgres e odoo gerenciados por gitops"
git branch -M main
git remote add origin [https://github.com/SEU_USUARIO/gitops-odoo.git](https://github.com/SEU_USUARIO/gitops-odoo.git)
git push -u origin main


(Não se esqueça de trocar SEU_USUARIO pelo seu usuário do Github).

Passo 4: Conectando o Argo CD

Agora dizemos ao Argo CD: "Olhe para esse repositório e faça acontecer".

Crie um arquivo novo fora da pasta (ou aplique direto via terminal) chamado app-argocd.yaml:

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '[https://github.com/SEU_USUARIO/gitops-odoo.git](https://github.com/SEU_USUARIO/gitops-odoo.git)' # TROQUE O USUARIO AQUI
    targetRevision: HEAD
    path: .
  destination:
    server: '[https://kubernetes.default.svc](https://kubernetes.default.svc)'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


Aplique no cluster:

kubectl apply -f app-argocd.yaml


Passo 5: Ver a Mágica Acontecer e Acessar o Odoo

Neste momento, o Argo CD identificou o seu repositório Git, leu os 3 arquivos e mandou criar tudo. O External Secrets leu o Vault e gerou a senha pro banco, o Postgres subiu, e o Odoo conectou no Postgres.

Acompanhe a criação dos Pods:

kubectl get pods -w


(Aguarde até que os pods do odoo e odoo-db fiquem com o status Running / 1/1)

Acesse o Odoo:
Como estamos no Minikube, precisamos liberar a porta para acessar o navegador:

minikube service odoo


Isso vai abrir o seu navegador automaticamente na tela de instalação do seu próprio Odoo gerenciado 100% via GitOps!

Resumo do que você alcançou:
Se você quiser mudar a versão do Odoo para a 17.0, você não usa mais o kubectl. Você altera a imagem no arquivo 03-odoo.yaml na sua máquina, dá um git push, e o Argo CD atualizará o Odoo sozinho em instantes!