apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RuanOnor/teste-lab.git' # TROQUE O USUARIO AQUI
    targetRevision: HEAD
    path: .
  destination:
    server: '[https://kubernetes.default.svc](https://kubernetes.default.svc)'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true